//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendingCoach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetItem
    {
        public System.Guid BudgetItemId { get; set; }
        public System.Guid BudgetId { get; set; }
        public string BudgetItemName { get; set; }
        public decimal BudgetItemAmount { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string BudgetItemCategory { get; set; }
        public string BudgetItemFrequency { get; set; }
        public int BudgetItemType { get; set; }
    }
}
