//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendingCoach.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Central : DbContext
    {
        public Central()
            : base("name=Central")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BudgetItem> BudgetItems { get; set; }
        public virtual DbSet<Budget> Budgets { get; set; }
        public virtual DbSet<L_SuggestedBudgetItem> L_SuggestedBudgetItem { get; set; }
        public virtual DbSet<L_Category> L_Category { get; set; }
        public virtual DbSet<L_SuggestedFrequency> L_SuggestedFrequency { get; set; }
        public virtual DbSet<TransactionItem> TransactionItems { get; set; }
        public virtual DbSet<WizardInstance> WizardInstances { get; set; }
        public virtual DbSet<L_WizardMapping> L_WizardMapping { get; set; }
        public virtual DbSet<L_MostImportantBudgetItemQuizItem> L_MostImportantBudgetItemQuizItem { get; set; }
        public virtual DbSet<WizardEmployer> WizardEmployers { get; set; }
    }
}
