//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendingCoach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_SuggestedFrequency
    {
        public System.Guid FrequencyId { get; set; }
        public string FrequencyName { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int Order { get; set; }
    }
}
