//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendingCoach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_WizardMapping
    {
        public System.Guid WizardMappingId { get; set; }
        public string WizardPage { get; set; }
        public string WizardFirstPrevPage { get; set; }
        public string WizardSecondPrevPage { get; set; }
        public string WizardThirdPrevPage { get; set; }
        public string WizardFirstNextPage { get; set; }
        public string WizardSecondNextPage { get; set; }
        public string WizardThirdNextPage { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
