//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendingCoach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionItem
    {
        public System.Guid TransactionItemId { get; set; }
        public System.Guid CustomerId { get; set; }
        public string TransactionItemName { get; set; }
        public decimal TransactionItemAmount { get; set; }
        public System.DateTime TransactionItemDate { get; set; }
        public Nullable<System.Guid> TransactionItemBudgetItem { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<System.Guid> PrimaryTransactionItem { get; set; }
        public Nullable<System.Guid> SecondaryTranscationItem { get; set; }
        public Nullable<int> TransactionItemType { get; set; }
        public string TransactionItemMemo { get; set; }
    }
}
