//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendingCoach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WizardInstance
    {
        public System.Guid WizardId { get; set; }
        public System.Guid BudgetId { get; set; }
        public string Position { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string PrevPosition { get; set; }
        public string InitialPurpose { get; set; }
        public string SubsequentPurpose { get; set; }
        public Nullable<System.Guid> MostImportantBudgetItem { get; set; }
        public string PrimaryName { get; set; }
        public string SpouseName { get; set; }
    }
}
