//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendingCoach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WizardEmployer
    {
        public System.Guid EmployerId { get; set; }
        public System.Guid WizardId { get; set; }
        public string EmployerName { get; set; }
        public string EmployerType { get; set; }
        public string EmployerUser { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
